---
Gemfile:
  required:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'puppet_litmus'
        git: 'https://github.com/puppetlabs/puppet_litmus.git'
      - gem: 'serverspec'
      - gem: 'hiera-puppet-helper'
      - gem: 'net-ssh'
      - gem: 'ed25519'
        version: '>= 1.2'
      - gem: 'bcrypt_pbkdf'
        version: '>= 1.0'

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
